version: "3"

services: 
  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"    
    volumes:
      - .:/rails_docker_app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: ''
      DB_HOST: db
  db:
    image: mysql:5.5
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/rails_docker_app
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
volumes:
  db_data:
    driver: local
  bundle:
    driver: local
